name: GitHub Classroom Workflow

on:
  - push
  - workflow_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install tqdm
        
      - name: Autograding
        if: github.actor != 'github-classroom[bot]'
        uses: actions/checkout@v4
        uses: education/autograding@v1
